"""Assemble the final Markdown documents from the pipeline state.

Assembly is deterministic: the LLM writes prose *sections*; the skeleton,
tables, table of contents, Mermaid diagram and appendices are built here from
the parsed IR, so structural facts (arguments, dependencies, config) are always
exact and never hallucinated.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from .. import __version__
from ..model.ir import ProjectInventory, WorkflowIR
from .lint import lint_markdown, md_anchor, md_cell

MERMAID_MAX_EDGES = 60


# --------------------------------------------------------------------------- #
# Technical documentation
# --------------------------------------------------------------------------- #

def render_documentation(state: dict | object) -> str:
    get = state.get if isinstance(state, dict) else lambda k, d=None: getattr(state, k, d)
    inv: ProjectInventory = get("inventory")
    narrative = get("narrative")
    summaries = get("summaries", {}) or {}
    findings = get("findings", []) or []
    gap_answers = get("gap_answers", []) or []
    warnings = get("warnings", []) or []

    title = inv.meta.name or Path(inv.root).name or "UiPath Process"
    sections: list[tuple[str, str]] = []

    sections.append(("Executive summary", narrative.executive_summary if narrative else ""))
    sections.append(("Project overview", _overview(inv)))
    sections.append(("Process description", narrative.process_description if narrative else ""))
    sections.append(("Architecture", _architecture(inv, narrative)))
    if inv.config_entries:
        sections.append(("Configuration", _configuration(inv)))
    sections.append(("Workflow reference", _workflow_reference(inv, summaries)))
    sections.append(("Exception handling and logging", _exceptions(narrative)))
    if narrative and narrative.external_systems:
        sections.append(("External systems", narrative.external_systems))
    if inv.log_digest.files:
        sections.append(("Execution log observations", _logs(inv)))
    sections.append(("Improvement suggestions", _findings(findings)))
    appendix = _appendix(inv, summaries, gap_answers, warnings)
    if appendix:
        sections.append(("Appendix: analysis notes", appendix))

    out: list[str] = [f"# {title} — Technical Documentation", ""]
    out.append(
        f"Generated by rpa-code-guardian v{__version__} on {date.today().isoformat()}. "
        "This document was produced by static analysis of the project sources; "
        "structural data (arguments, dependencies, configuration) is extracted "
        "directly from the files."
    )
    out.append("")
    out.append("## Contents")
    out.append("")
    for heading, _ in sections:
        out.append(f"- [{heading}](#{md_anchor(heading)})")
    for heading, body in sections:
        out.append("")
        out.append(f"## {heading}")
        out.append("")
        out.append(body.strip() or "(not available)")
    return lint_markdown("\n".join(out))


def _overview(inv: ProjectInventory) -> str:
    m = inv.meta
    rows = [
        ("Project name", m.name or "(unnamed)"),
        ("Description", m.description or "-"),
        ("Entry point", inv.call_graph.entry),
        ("Studio version", m.studio_version or "-"),
        ("Target framework", m.target_framework or "-"),
        ("Expression language", m.expression_language or "-"),
        ("Workflows", str(len(inv.workflows))),
        ("REFramework", "Yes — " + "; ".join(inv.reframework_evidence) if inv.is_reframework else "No"),
    ]
    lines = ["| Item | Value |", "|------|-------|"]
    lines += [f"| {md_cell(k)} | {md_cell(v)} |" for k, v in rows]
    if m.dependencies:
        lines += ["", "### Package dependencies", "", "| Package | Version |", "|---------|---------|"]
        lines += [f"| {md_cell(k)} | {md_cell(v)} |" for k, v in sorted(m.dependencies.items())]
    return "\n".join(lines)


def _architecture(inv: ProjectInventory, narrative) -> str:
    parts: list[str] = []
    if narrative and narrative.architecture:
        parts.append(narrative.architecture)
    entry_ir = inv.workflows.get(inv.call_graph.entry)
    if entry_ir is not None and entry_ir.states:
        parts.append("State machine states of the entry workflow: " + ", ".join(entry_ir.states) + ".")
    mermaid = _mermaid(inv)
    if mermaid:
        parts.append("### Invocation graph\n\n" + mermaid)
    return "\n\n".join(parts)


def _mermaid(inv: ProjectInventory) -> str:
    edges: list[tuple[str, str]] = []
    for src in sorted(inv.call_graph.edges):
        for dst in inv.call_graph.edges[src]:
            edges.append((src, dst))
    if not edges:
        return ""
    if len(edges) > MERMAID_MAX_EDGES:
        # Keep the neighborhood of the entry point (depth 2) so the diagram stays readable.
        keep = {inv.call_graph.entry}
        for _ in range(2):
            keep |= {d for s, d in edges if s in keep}
        edges = [(s, d) for s, d in edges if s in keep and (d in keep or s == inv.call_graph.entry)]
        edges = edges[:MERMAID_MAX_EDGES]
    ids: dict[str, str] = {}

    def nid(path: str) -> str:
        if path not in ids:
            ids[path] = f"n{len(ids)}"
        return ids[path]

    def label(path: str) -> str:
        stem = path.rsplit("/", 1)[-1].removesuffix(".xaml")
        return re.sub(r'["\[\]{}]', "", stem)

    lines = ["```mermaid", "graph TD"]
    for src, dst in edges:
        lines.append(f'    {nid(src)}["{label(src)}"] --> {nid(dst)}["{label(dst)}"]')
    lines.append("```")
    return "\n".join(lines)


def _configuration(inv: ProjectInventory) -> str:
    lines = [f"Configuration workbook: `{inv.config_file}`.", ""]
    sheets: dict[str, list] = {}
    for e in inv.config_entries:
        sheets.setdefault(e.sheet, []).append(e)
    for sheet, entries in sheets.items():
        lines += [f"### {sheet}", "", "| Name | Value | Description |", "|------|-------|-------------|"]
        lines += [f"| {md_cell(e.name)} | {md_cell(e.value)} | {md_cell(e.description) or '-'} |" for e in entries]
        lines.append("")
    return "\n".join(lines)


def _workflow_reference(inv: ProjectInventory, summaries: dict) -> str:
    lines: list[str] = []
    boilerplate: list[tuple[str, str]] = []

    for path in sorted(inv.workflows):
        ir = inv.workflows[path]
        summary = summaries.get(path)
        if summary is not None and summary.is_boilerplate:
            boilerplate.append((path, summary.one_liner or "Standard REFramework template workflow."))
            continue
        lines.append(f"### {path}")
        lines.append("")
        if summary is not None:
            lines.append(summary.purpose)
            lines.append("")
        elif ir.annotation:
            lines.append(ir.annotation)
            lines.append("")
        if ir.arguments:
            lines += ["| Argument | Direction | Type |", "|----------|-----------|------|"]
            lines += [f"| {md_cell(a.name)} | {a.direction} | {md_cell(a.type)} |" for a in ir.arguments]
            lines.append("")
        if summary is not None and summary.key_logic:
            lines.append("Key steps:")
            lines.append("")
            lines += [f"1. {step}" for step in summary.key_logic]
            lines.append("")
        if summary is not None and summary.error_handling and summary.error_handling.lower() != "none":
            lines.append(f"Error handling: {summary.error_handling}")
            lines.append("")
        if summary is not None and summary.external_systems:
            lines.append("External systems: " + ", ".join(summary.external_systems) + ".")
            lines.append("")

    if boilerplate:
        lines += [
            "### Standard framework workflows",
            "",
            "The following workflows are unmodified (or minimally modified) REFramework template components:",
            "",
            "| Workflow | Role |",
            "|----------|------|",
        ]
        lines += [f"| {md_cell(p)} | {md_cell(d)} |" for p, d in boilerplate]
    return "\n".join(lines)


def _exceptions(narrative) -> str:
    parts = []
    if narrative and narrative.exception_strategy:
        parts.append(narrative.exception_strategy)
    if narrative and narrative.logging_observability:
        parts.append(narrative.logging_observability)
    return "\n\n".join(parts)


def _logs(inv: ProjectInventory) -> str:
    d = inv.log_digest
    lines = [
        f"Log files analyzed: {', '.join(f'`{f}`' for f in d.files)} "
        f"({d.total_lines} lines, {d.first_timestamp or '?'} to {d.last_timestamp or '?'})."
    ]
    if d.level_counts:
        lines += ["", "| Level | Count |", "|-------|-------|"]
        lines += [f"| {k} | {v} |" for k, v in sorted(d.level_counts.items())]
    if d.error_samples:
        lines += ["", "Representative errors and warnings:", ""]
        lines += [f"- {md_cell(s)}" for s in d.error_samples]
    return "\n".join(lines)


def _findings(findings: list) -> str:
    if not findings:
        return "No improvement suggestions were identified by the analysis."
    lines: list[str] = []
    for severity in ("High", "Medium", "Low"):
        group = [f for f in findings if f.severity == severity]
        if not group:
            continue
        lines += [f"### {severity} priority", ""]
        lines += ["| Location | Category | Issue | Recommendation |",
                  "|----------|----------|-------|----------------|"]
        lines += [
            f"| {md_cell(f.location) or '-'} | {md_cell(f.category)} | {md_cell(f.description)} | {md_cell(f.recommendation) or '-'} |"
            for f in group
        ]
        lines.append("")
    return "\n".join(lines)


def _appendix(inv: ProjectInventory, summaries: dict, gap_answers: list, warnings: list) -> str:
    lines: list[str] = []
    compressed = sum(len(ir.to_context()) for ir in inv.workflows.values())
    lines.append(
        f"Analysis coverage: {len(summaries)} of {len(inv.workflows)} workflows summarized; "
        f"{inv.total_xaml_chars} characters of XAML reduced to {compressed} characters of "
        "parsed representation before analysis."
    )
    if inv.skipped_files:
        lines += ["", "Files skipped during ingestion:", ""]
        lines += [f"- {s}" for s in inv.skipped_files]
    if gap_answers:
        lines += ["", "### Verified clarifications", ""]
        for a in gap_answers:
            ev = f" (evidence: {', '.join(a.evidence)})" if a.evidence else ""
            lines.append(f"- **{md_cell(a.question)}** {md_cell(a.answer)}{ev}")
    if warnings:
        lines += ["", "### Analysis warnings", ""]
        lines += [f"- {md_cell(w)}" for w in warnings]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Compliance report
# --------------------------------------------------------------------------- #

def render_compliance(state: dict | object) -> str:
    get = state.get if isinstance(state, dict) else lambda k, d=None: getattr(state, k, d)
    inv: ProjectInventory = get("inventory")
    requirements = get("requirements", []) or []
    compliance: dict = get("compliance", {}) or {}

    title = inv.meta.name or Path(inv.root).name or "UiPath Process"
    out: list[str] = [f"# {title} — PDD Compliance Report", ""]
    out.append(
        f"Generated by rpa-code-guardian v{__version__} on {date.today().isoformat()}."
    )
    out.append("")
    out.append("## Scope and method")
    out.append("")
    out.append(
        f"{len(requirements)} requirements were extracted from the Process Definition "
        "Document and assessed against the implemented project "
        f"({len(inv.workflows)} workflows). Each requirement was verified against the "
        "static analysis of the source workflows and the project configuration; "
        "verdicts cite the implementing workflows as evidence. Runtime behavior was "
        "not executed as part of this assessment."
    )

    counts: dict[str, int] = {}
    for item in compliance.values():
        counts[item.verdict] = counts.get(item.verdict, 0) + 1
    out += ["", "## Verdict summary", "", "| Verdict | Count |", "|---------|-------|"]
    for verdict in ("Compliant", "Partially compliant", "Non-compliant", "Not verifiable"):
        if counts.get(verdict):
            out.append(f"| {verdict} | {counts[verdict]} |")

    out += [
        "", "## Requirements traceability matrix", "",
        "| ID | Requirement | Verdict | Evidence |",
        "|----|-------------|---------|----------|",
    ]
    for req in requirements:
        item = compliance.get(req.id)
        verdict = item.verdict if item else "Not assessed"
        evidence = ", ".join(item.evidence) if item and item.evidence else "-"
        out.append(f"| {req.id} | {md_cell(req.text)} | {verdict} | {md_cell(evidence)} |")

    deviations = [
        (req, compliance[req.id]) for req in requirements
        if req.id in compliance and compliance[req.id].verdict != "Compliant"
    ]
    out += ["", "## Gaps and deviations", ""]
    if not deviations:
        out.append("No gaps or deviations were identified.")
    for req, item in deviations:
        out += [f"### {req.id} — {item.verdict}", "", f"Requirement: {req.text}", ""]
        out.append(item.justification)
        if item.gap:
            out += ["", f"Gap: {item.gap}"]
        out.append("")

    total = len(requirements)
    ok = counts.get("Compliant", 0)
    out += ["", "## Conclusion", ""]
    if total == 0:
        out.append("No verifiable requirements could be extracted from the provided PDD.")
    else:
        out.append(
            f"{ok} of {total} extracted requirements are fully compliant"
            f" ({counts.get('Partially compliant', 0)} partially compliant,"
            f" {counts.get('Non-compliant', 0)} non-compliant,"
            f" {counts.get('Not verifiable', 0)} not verifiable)."
            " Items listed under Gaps and deviations should be reviewed with the"
            " process owner before sign-off."
        )
    return lint_markdown("\n".join(out))
